Numpy - numerical python - fundamental package for scientific computing with python


In [3]:
import numpy as np # as is alias

In [5]:
list = [11,2,3,"data", 3+5j, True, 2.3]

In [6]:
type (list) # it is heterogeneous, it stores different data types, numpy is faster than list

list

numpy stores the data in a numpy array
array is container or data structure - used to store the same data types

why numpy ? <br>
c is one of the fastest programming language and numpy is built by using c, numpy computation is fast<br>
it is fast due to array since it stores homogeneous data <br>
it is contigues memory location<br>


In [19]:
a = [1,2,3,4,5]

In [21]:
a1 = np.array(a)

In [22]:
a1

array([1, 2, 3, 4, 5])

In [23]:
type(a1) # data type

numpy.ndarray

In [25]:
a1.ndim # dimension 

1

In [26]:
a1[0] # we can access the elements

1

In [27]:
a1[0] = 1000 # array is mutable , we can modify the elements

In [28]:
a1

array([1000,    2,    3,    4,    5])

In [33]:
np.zeros(6) # it will give 6 zeroes

array([0., 0., 0., 0., 0., 0.])

In [48]:
s = np.zeros((3,3))

In [49]:
s

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
s.ndim

2

In [55]:
s = np.zeros((1,3,3)) # we can add no dimension by adding 1

In [56]:
s

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
s = np.zeros((1,1,3,3))

In [58]:
s

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [75]:
s.ndim

4

In [50]:
s + 8 # index addition

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [52]:
s - 2 # index subsraction

array([[-2., -2., -2.],
       [-2., -2., -2.],
       [-2., -2., -2.]])

In [53]:
s * 3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones(3)

array([1., 1., 1.])

In [61]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
v = np.ones((3,4), dtype = int) # it converts float into integer

In [64]:
v

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [65]:
v[1]

array([1, 1, 1, 1])

In [66]:
v[2,3]

1

In [67]:
np.twos(3) # does not exist

AttributeError: module 'numpy' has no attribute 'twos'

In [69]:
z = np.array([[2,3],[3,2]])

In [70]:
z # we get two dimensional array

array([[2, 3],
       [3, 2]])

In [71]:
z[1] # we can access and it takes 1st row

array([3, 2])

In [72]:
z[0] # we can access and it takes 1st row

array([2, 3])

In [73]:
z.ndim

2

In [79]:
np.fromfunction((lambda a,j : a==j), (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [80]:
np.fromfunction((lambda a,j : a==j), (3,2))

array([[ True, False],
       [False,  True],
       [False, False]])

In [81]:
np.fromfunction((lambda a,j : a == j), (2,4))

array([[ True, False, False, False],
       [False,  True, False, False]])

In [82]:
np.eye(3) # return a 2d array with ones on the diagonal and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
np.eye(5, dtype = int) # it converts float into integer

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [86]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [88]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

random numbers related concept in numpy

In [89]:
import numpy as np

In [93]:
np.random.randint(1,5)

4

In [95]:
np.random.rand(1)

array([0.42555675])

In [99]:
d = [1,2,3,4,5]

In [100]:
np.random.shuffle(d) # elements shuffled

In [101]:
d

[5, 2, 1, 3, 4]

In [110]:
arr = np.random.randint(1,6, size = (3,3))

In [111]:
arr

array([[3, 1, 2],
       [4, 1, 1],
       [1, 4, 3]])

In [112]:
arr.ndim

2

In [113]:
arr.size

9

In [114]:
arr.shape

(3, 3)

In [120]:
arr2 = arr.reshape(1,3,3) # we can convert to 3 dimesional array

In [121]:
arr2

array([[[3, 1, 2],
        [4, 1, 1],
        [1, 4, 3]]])

In [122]:
arr2.ndim

3

In [123]:
arr = np.random.randint(1,6, size = (3,4))

In [124]:
arr

array([[4, 2, 2, 3],
       [1, 5, 5, 1],
       [3, 2, 3, 3]])

reshape

In [125]:
arr.reshape(2,6)

array([[4, 2, 2, 3, 1, 5],
       [5, 1, 3, 2, 3, 3]])

In [126]:
arr.reshape(2,-1)

array([[4, 2, 2, 3, 1, 5],
       [5, 1, 3, 2, 3, 3]])

In [127]:
arr.reshape(-1,6)

array([[4, 2, 2, 3, 1, 5],
       [5, 1, 3, 2, 3, 3]])

In [128]:
arr.reshape(12,1).base # if we want to know the original array

array([[4, 2, 2, 3],
       [1, 5, 5, 1],
       [3, 2, 3, 3]])

In [129]:
arr

array([[4, 2, 2, 3],
       [1, 5, 5, 1],
       [3, 2, 3, 3]])

In [130]:
arr.reshape(1,1,3,4)

array([[[[4, 2, 2, 3],
         [1, 5, 5, 1],
         [3, 2, 3, 3]]]])

In [133]:
arr.reshape(2,2,3)

array([[[4, 2, 2],
        [3, 1, 5]],

       [[5, 1, 3],
        [2, 3, 3]]])

In [134]:
arr.reshape(3,2,2)

array([[[4, 2],
        [2, 3]],

       [[1, 5],
        [5, 1]],

       [[3, 2],
        [3, 3]]])

In [135]:
arrs = np.random.randint(1,10,(5,6))

In [136]:
arrs

array([[3, 2, 4, 6, 9, 2],
       [9, 8, 9, 2, 1, 6],
       [5, 2, 6, 5, 8, 7],
       [1, 1, 3, 5, 6, 9],
       [9, 8, 6, 2, 2, 2]])

In [137]:
arrs>2

array([[ True, False,  True,  True,  True, False],
       [ True,  True,  True, False, False,  True],
       [ True, False,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False]])

In [138]:
arrs<4

array([[ True,  True, False, False, False,  True],
       [False, False, False,  True,  True, False],
       [False,  True, False, False, False, False],
       [ True,  True,  True, False, False, False],
       [False, False, False,  True,  True,  True]])

In [139]:
arrs.shape

(5, 6)

In [140]:
arrs.size

30

In [141]:
arrs[arrs>3]

array([4, 6, 9, 9, 8, 9, 6, 5, 6, 5, 8, 7, 5, 6, 9, 9, 8, 6])

In [142]:
arrs[arrs<=2]

array([2, 2, 2, 1, 2, 1, 1, 2, 2, 2])

In [143]:
arrs[arrs>=5]

array([6, 9, 9, 8, 9, 6, 5, 6, 5, 8, 7, 5, 6, 9, 9, 8, 6])

In [145]:
arrs[0]

array([3, 2, 4, 6, 9, 2])

In [146]:
arrs[0][2]

4

In [147]:
arrs[0:3]

array([[3, 2, 4, 6, 9, 2],
       [9, 8, 9, 2, 1, 6],
       [5, 2, 6, 5, 8, 7]])

In [148]:
arrs[2:3]

array([[5, 2, 6, 5, 8, 7]])

In [149]:
arrs[0:4]

array([[3, 2, 4, 6, 9, 2],
       [9, 8, 9, 2, 1, 6],
       [5, 2, 6, 5, 8, 7],
       [1, 1, 3, 5, 6, 9]])

In [150]:
arrs[0:4,[0,2]]

array([[3, 4],
       [9, 9],
       [5, 6],
       [1, 3]])

In [152]:
r  = np.random.randint(1,4,(3,4))

In [153]:
r

array([[2, 2, 3, 1],
       [2, 2, 1, 2],
       [1, 3, 3, 1]])

In [155]:
r.flatten()

array([2, 2, 3, 1, 2, 2, 1, 2, 1, 3, 3, 1])

In [156]:
np.expand_dims(r,axis = 0)

array([[[2, 2, 3, 1],
        [2, 2, 1, 2],
        [1, 3, 3, 1]]])

In [157]:
np.expand_dims(r, axis = 1)

array([[[2, 2, 3, 1]],

       [[2, 2, 1, 2]],

       [[1, 3, 3, 1]]])

In [159]:
c = np.array([1,2,3])

In [160]:
c

array([1, 2, 3])

In [161]:
np.expand_dims(c, axis = 1)

array([[1],
       [2],
       [3]])

In [162]:
np.expand_dims(c, axis = 0 )

array([[1, 2, 3]])

In [163]:
np.repeat(c,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [164]:
np.repeat(r,30)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [165]:
np.repeat(r,10, axis = 1)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

operation on numpy string array

In [166]:
q = np.array(['data', 'science'])

In [167]:
q

array(['data', 'science'], dtype='<U7')

In [169]:
np.char.upper(q)

array(['DATA', 'SCIENCE'], dtype='<U7')

In [170]:
np.char.lower(q)

array(['data', 'science'], dtype='<U7')

In [171]:
np.char.capitalize(q)

array(['Data', 'Science'], dtype='<U7')

mathematical function

In [181]:
f = np.array([2,5,6,8,9])

In [182]:
np.sin(f)

array([ 0.90929743, -0.95892427, -0.2794155 ,  0.98935825,  0.41211849])

In [183]:
np.cos(f)

array([-0.41614684,  0.28366219,  0.96017029, -0.14550003, -0.91113026])

In [184]:
np.tan(f)

array([-2.18503986, -3.38051501, -0.29100619, -6.79971146, -0.45231566])

In [185]:
np.mean(f)

6.0

In [186]:
np.median(f)

6.0

In [187]:
np.exp(f)

array([7.38905610e+00, 1.48413159e+02, 4.03428793e+02, 2.98095799e+03,
       8.10308393e+03])

In [189]:
np.log10(f)

array([0.30103   , 0.69897   , 0.77815125, 0.90308999, 0.95424251])

In [192]:
np.power(f,3)

array([  8, 125, 216, 512, 729])

In [193]:
np.max(f)

9

In [194]:
np.min(f)

2

In [195]:
np.add(f,2)

array([ 4,  7,  8, 10, 11])

In [199]:
np.multiply(f,2)

array([ 4, 10, 12, 16, 18])

In [201]:
np.mod(f,3) # return element wise reminder

array([2, 2, 0, 2, 0])

In [202]:
np.sort(f)

array([2, 5, 6, 8, 9])